fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "contact@cgofficiel.fr" 
        sender_name: "cgofficiel.fr" 
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   '@FOSUser/Resetting/resetting_email.html.twig'
    registration:
        confirmation:
            enabled: true
            template:   '@FOSUser/Registration/registration_email.html.twig'
        form:
            type: App\Form\UserType
